wandb:
  entity: xinpw8
  project: pokemon
  group: pokegym_refactor

debug:
  env:
    headless: False
    stream_wrapper: False
  train:
    device: cpu
    compile: False
    compile_mode: default
    num_envs: 1
    envs_per_worker: 1
    envs_per_batch: 1
    batch_size: 128
    batch_rows: 32
    bptt_horizon: 4
    total_timesteps: 500_000_000
    save_checkpoint: True
    checkpoint_interval: 4
    save_overlay: True
    overlay_interval: 4
    verbose: True
    env_pool: False

env:
  headless: True
  save_final_state: True
  print_rewards: True
  video_dir: video
  state_dir: pyboy_states
  init_state: Bulbasaur
  action_freq: 24
  max_steps: 20480
  save_video: False
  fast_video: False
  frame_stacks: 1
  perfect_ivs: True
  reduce_res: True
  two_bit: False

train:
  seed: 1
  torch_deterministic: True
  device: cuda
  compile: True
  compile_mode: "reduce-overhead"
  float32_matmul_precision: "high"
  total_timesteps: 100_000_000_000
  batch_size: 65536 
  learning_rate: 1.75e-4
  anneal_lr: False
  gamma: 0.998
  gae_lambda: 0.95
  num_minibatches: 4
  update_epochs: 3
  norm_adv: True
  clip_coef: 0.1
  clip_vloss: True
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  target_kl: ~
  batch_rows: 128
  bptt_horizon: 16 
  vf_clip_coef: 0.1

  num_envs: 96
  envs_per_worker: 1
  envs_per_batch: 32
  env_pool: True

  verbose: True
  data_dir: runs
  save_checkpoint: False
  checkpoint_interval: 200
  save_overlay: True
  overlay_interval: 200
  cpu_offload: True
  pool_kernel: [0]
  log_frequency: 2000

wrappers:
  baseline:
    - stream_wrapper.StreamWrapper:
        user: xinpw8

  stream_only:
    - stream_wrapper.StreamWrapper:
        user: xinpw8 

rewards:
  teach_cut_v1.RewardWrapper:
    reward:  
  # baseline.TeachCutReplicationEnv:
  #   reward:
  #     event: 1.0
  #     bill_saved: 5.0
  #     seen_pokemon: 4.0
  #     caught_pokemon: 4.0
  #     moves_obtained: 4.0
  #     hm_count: 10.0
  #     level: 1.0
  #     badges: 10.0
  #     exploration: 0.02
  #     cut_coords: 1.0
  #     cut_tiles: 1.0
  #     start_menu: 0.01
  #     pokemon_menu: 0.1
  #     stats_menu: 0.1
  #     bag_menu: 0.1

policies:
  multi_convolutional.MultiConvolutionalPolicy:
    policy:
      hidden_size: 512

    recurrent:
      # Assumed to be in the same module as the policy
      name: RecurrentMultiConvolutionalWrapper
      input_size: 512
      hidden_size: 512
      num_layers: 1